### ISSUE TITLE
Are you Maltese by any chance?

### ISSUE THREAD

**Issue by kylebriffa7** [deniscerri/deniscerri#1]
Hi bro 

I have been using YTDLnis and noticed your username ending in a popular maltese surname. I was wondering whether you are maltese like me.

In any case, amazing job on the app, it's a very useful app for me.

Regards,
Kyle

**Comment by malionsara** [comment]
He is a pure Albanian Gango

**Comment by deniscerri** [comment]
> He is a pure Albanian Gango

😂😂 po ti
